# Generated by Django 5.2.12 on 2026-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SzablonGeneratora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('typ', models.CharField(max_length=50)),
                ('pola', models.TextField(blank=True, null=True)),
                ('tresc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
