# Generated by Django 5.2.12 on 2026-05-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='szablongeneratora',
            options={'verbose_name': 'Szablon generatora', 'verbose_name_plural': 'Szablony generatora'},
        ),
    ]
