# Generated by Django 5.2.12 on 2026-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZgloszenieProblemu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_i_godzina_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('autor_zgloszenia', models.CharField(max_length=150)),
                ('temat_zgloszenia', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('modul_aplikacji', models.CharField(choices=[('oferta_publiczna', 'Oferta Publiczna'), ('panel_oferty', 'Panel Zarządzania Ofertą'), ('rejestracja', 'Rejestracja i Zgłoszenia'), ('inny', 'Inny moduł / Ogólne')], default='inny', max_length=50)),
                ('zalacznik_graficzny', models.ImageField(blank=True, null=True, upload_to='issues_attachments/')),
            ],
        ),
    ]
