# Generated by Django 5.2.12 on 2026-05-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OfertaPubliczna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgoda_rodo', models.BooleanField(default=False)),
                ('status', models.CharField(default='Nowe', max_length=50)),
                ('data_i_godzina_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('szkolenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejestracje', to='OfertaPubliczna.szkolenie')),
            ],
        ),
    ]
