# Generated by Django 5.2.12 on 2026-05-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejestracja',
            options={'verbose_name': 'Rejestracja', 'verbose_name_plural': 'Rejestracje'},
        ),
    ]
