# Generated by Django 5.2.12 on 2026-05-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publikuj', models.BooleanField(default=True)),
                ('kolejnosc', models.IntegerField(default=0)),
                ('nazwa', models.CharField(max_length=255)),
                ('kategoria_nadrzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podkategorie', to='OfertaPubliczna.kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publikuj', models.BooleanField(default=True)),
                ('kolejnosc', models.IntegerField(default=0)),
                ('liczba_godzin', models.IntegerField()),
                ('numer', models.CharField(max_length=50, unique=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szkolenia', to='OfertaPubliczna.kategorie')),
            ],
        ),
    ]
