# Generated by Django 5.2.12 on 2026-05-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaPubliczna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie',
            options={'verbose_name': 'Szkolenie', 'verbose_name_plural': 'Szkolenia'},
        ),
    ]
